plugins {
    kotlin("multiplatform") version "2.3.20"
    kotlin("plugin.serialization") version "2.3.20"
    kotlin("plugin.compose") version "2.3.20"
    id("com.android.library") version "8.13.0"
    id("maven-publish")
    // API reference for get-milano.dev/sdk/libs/compose, generated by the
    // release pipeline.
    id("org.jetbrains.dokka") version "2.0.0"
}

group = "dev.get-milano"
// The release workflow passes -PmilanoVersion=<x.y.z>; local builds default.
version = (findProperty("milanoVersion") as? String) ?: "0.0.0-dev"

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvmToolchain(17)

    // The engine core lives in commonMain: pure Kotlin, no platform APIs by
    // construction. The jvm target carries the conformance harness and covers
    // desktop; androidTarget keeps the Android library buildable from M1 on.
    jvm()
    androidTarget {
        publishLibraryVariants("release")
    }

    sourceSets {
        commonMain.dependencies {
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            // The engine renders nothing itself: only the Compose runtime,
            // no UI artifacts.
            api("org.jetbrains.compose.runtime:runtime:1.9.0")
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

android {
    namespace = "dev.getmilano"
    compileSdk = 36
    defaultConfig {
        minSdk = 26
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name = "Milano SDK (Compose engine)"
            description = "Document-Driven UI for Compose: documents in, native UI out, validated by a strict gate."
            url = "https://get-milano.dev"
            licenses {
                license {
                    name = "Apache License, Version 2.0"
                    url = "https://www.apache.org/licenses/LICENSE-2.0"
                }
            }
            developers {
                developer {
                    name = "Ezequiel (kimi) Aceto"
                    email = "ezequiel.aceto@gmail.com"
                    url = "https://kimi.blog"
                }
            }
            scm {
                url = "https://github.com/get-milano/sdk"
                connection = "scm:git:https://github.com/get-milano/sdk.git"
            }
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/get-milano/sdk")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
