plugins {
    kotlin("multiplatform") version "2.3.20"
    kotlin("plugin.serialization") version "2.3.20"
    kotlin("plugin.compose") version "2.3.20"
    id("com.android.kotlin.multiplatform.library") version "9.3.1"
    id("maven-publish")
    // Central requires every release artifact to carry a PGP signature.
    id("signing")
    // API reference for get-milano.dev/sdk/libs/compose, generated by the
    // release pipeline.
    id("org.jetbrains.dokka") version "2.0.0"
    // Coverage for the docs site's report, published per release.
    id("org.jetbrains.kotlinx.kover") version "0.9.9"
}

group = "dev.get-milano"
// The release workflow passes -PmilanoVersion=<x.y.z>; local builds default.
version = (findProperty("milanoVersion") as? String) ?: "0.0.0-dev"

repositories {
    mavenCentral()
    google()
}

// The bindings generator's Kotlin golden compiles with the JVM test
// sources, so a generator change that no longer compiles against this
// engine fails jvmTest (scripts/verify-bindings.mjs names the check). It
// is staged from the specs checkout when one is present, found the way
// the conformance harness finds its vectors: MILANO_SPECS_DIR, or the
// sibling checkout.
val specsDirectory: File? =
    (System.getenv("MILANO_SPECS_DIR")?.takeIf { it.isNotEmpty() }?.let(::File) ?: rootDir.resolve("../../../specs"))
        .takeIf { it.isDirectory }
val bindingsGolden: File? = specsDirectory?.resolve("tools/testdata/expected_bindings.kt")?.takeIf { it.isFile }
val stageBindingsGolden by tasks.registering(Copy::class) {
    onlyIf { bindingsGolden != null }
    bindingsGolden?.let { from(it) }
    into(layout.buildDirectory.dir("bindings-golden"))
}

// The conformance vectors are read at test time, so they are an input:
// a changed suite reruns the tests instead of replaying an up-to-date
// result. Gradle cannot know that on its own.
tasks.withType<Test>().configureEach {
    specsDirectory?.resolve("conformance")?.let { suite ->
        inputs.dir(suite).withPathSensitivity(PathSensitivity.RELATIVE)
    }
}

kotlin {
    jvmToolchain(17)

    // The engine core lives in commonMain: pure Kotlin, no platform APIs by
    // construction. The jvm target carries the conformance harness and covers
    // desktop; the android target keeps the library buildable from M1 on.
    // Since AGP 9 the Android target is declared here rather than in a
    // separate android { } block, and AGP compiles the Kotlin itself.
    jvm()
    android {
        namespace = "dev.getmilano"
        compileSdk = 36
        minSdk = 26
        // Compiling against the newest SDK is not a demand on consumers.
        // The engine is pure Kotlin over the Compose runtime and touches no
        // platform API beyond what minSdk already implies, so nothing here
        // constrains what an app compiles against. Without this, AGP stamps
        // minCompileSdk = compileSdk into the AAR and every app on an older
        // one fails to resolve it; 1 is what AGP 8 published, and the CI
        // gate asserts it stays there.
        aarMetadata {
            minCompileSdk = 1
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            // The engine renders nothing itself: only the Compose runtime,
            // no UI artifacts.
            api("org.jetbrains.compose.runtime:runtime:1.9.0")
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        jvmTest {
            kotlin.srcDir(stageBindingsGolden)
        }
    }
}

// Where the Central Portal bundle is assembled, named once so the chain
// that builds the path does not have to be written inside a repository
// block (ktlint would wrap it across four lines there).
val centralBundle = layout.buildDirectory.dir("central-bundle")

// Maven Central requires a javadoc jar beside every artifact. Dokka
// already produces this engine's reference, so the jar carries the real
// documentation rather than an empty placeholder.
val javadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
    from(tasks.named("dokkaGeneratePublicationHtml"))
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        artifact(javadocJar)
        pom {
            name = "Milano SDK (Compose engine)"
            description = "Document-Driven UI for Compose: documents in, native UI out, validated by a strict gate."
            url = "https://get-milano.dev"
            licenses {
                license {
                    name = "Apache License, Version 2.0"
                    url = "https://www.apache.org/licenses/LICENSE-2.0"
                }
            }
            developers {
                developer {
                    name = "Ezequiel (kimi) Aceto"
                    email = "ezequiel.aceto@gmail.com"
                    url = "https://kimi.blog"
                }
            }
            scm {
                url = "https://github.com/get-milano/sdk"
                connection = "scm:git:https://github.com/get-milano/sdk.git"
            }
        }
    }
    repositories {
        // Maven Central is where Android and JVM consumers get the engine.
        // A release is uploaded as one bundle to the Central Portal, which
        // is assembled here first: publishing to a directory produces the
        // exact repository layout the Portal expects, checksums included.
        maven {
            name = "CentralBundle"
            url = centralBundle.get().asFile.toURI()
        }
        // Snapshots have no bundle step and no staging: they go straight to
        // Central's snapshot repository, which is why a -SNAPSHOT version
        // can be cut by hand between releases.
        maven {
            name = "CentralSnapshots"
            url = uri("https://central.sonatype.com/repository/maven-snapshots/")
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_TOKEN")
            }
        }
        // Kept beside Central: the release page's AAR and JAR are built from
        // the same job, and some consumers already resolve from here.
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/get-milano/sdk")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

signing {
    // Only when a key is present: local builds, GitHub Packages, and
    // snapshots need no signature, and requiring one would make every
    // developer machine carry a private key.
    val key = System.getenv("SIGNING_KEY")
    if (!key.isNullOrBlank()) {
        useInMemoryPgpKeys(key, System.getenv("SIGNING_PASSWORD") ?: "")
        sign(publishing.publications)
    }
}

// Kotlin Multiplatform wires several publications to one set of signing
// tasks, which Gradle cannot infer an ordering for on its own.
tasks.withType<AbstractPublishToMaven>().configureEach {
    dependsOn(tasks.withType<Sign>())
}
