plugins {
    kotlin("multiplatform") version "2.3.20"
    kotlin("plugin.serialization") version "2.3.20"
    kotlin("plugin.compose") version "2.3.20"
    id("com.android.kotlin.multiplatform.library") version "9.3.1"
    id("maven-publish")
    // API reference for get-milano.dev/sdk/libs/compose, generated by the
    // release pipeline.
    id("org.jetbrains.dokka") version "2.0.0"
    // Coverage for the docs site's report, published per release.
    id("org.jetbrains.kotlinx.kover") version "0.9.9"
}

group = "dev.get-milano"
// The release workflow passes -PmilanoVersion=<x.y.z>; local builds default.
version = (findProperty("milanoVersion") as? String) ?: "0.0.0-dev"

repositories {
    mavenCentral()
    google()
}

kotlin {
    jvmToolchain(17)

    // The engine core lives in commonMain: pure Kotlin, no platform APIs by
    // construction. The jvm target carries the conformance harness and covers
    // desktop; the android target keeps the library buildable from M1 on.
    // Since AGP 9 the Android target is declared here rather than in a
    // separate android { } block, and AGP compiles the Kotlin itself.
    jvm()
    android {
        namespace = "dev.getmilano"
        compileSdk = 36
        minSdk = 26
        // Compiling against the newest SDK is not a demand on consumers.
        // The engine is pure Kotlin over the Compose runtime and touches no
        // platform API beyond what minSdk already implies, so nothing here
        // constrains what an app compiles against. Without this, AGP stamps
        // minCompileSdk = compileSdk into the AAR and every app on an older
        // one fails to resolve it; 1 is what AGP 8 published, and the CI
        // gate asserts it stays there.
        aarMetadata {
            minCompileSdk = 1
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            // The engine renders nothing itself: only the Compose runtime,
            // no UI artifacts.
            api("org.jetbrains.compose.runtime:runtime:1.9.0")
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name = "Milano SDK (Compose engine)"
            description = "Document-Driven UI for Compose: documents in, native UI out, validated by a strict gate."
            url = "https://get-milano.dev"
            licenses {
                license {
                    name = "Apache License, Version 2.0"
                    url = "https://www.apache.org/licenses/LICENSE-2.0"
                }
            }
            developers {
                developer {
                    name = "Ezequiel (kimi) Aceto"
                    email = "ezequiel.aceto@gmail.com"
                    url = "https://kimi.blog"
                }
            }
            scm {
                url = "https://github.com/get-milano/sdk"
                connection = "scm:git:https://github.com/get-milano/sdk.git"
            }
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/get-milano/sdk")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
