/// <reference types="expo/types" />

// Expo's ambient types, which declare the EXPO_PUBLIC_* environment
// variables the dev screen switch reads. Generated by Expo in a fresh app;
// kept here because this project's tsconfig does not extend expo/tsconfig.
