# The docs site, buildable locally exactly as GitHub Pages builds it:
#
#   bundle install
#   bundle exec jekyll serve --baseurl ""
#
# The release workflow builds with `--baseurl /sdk`, the path the site is
# served from under get-milano.dev.
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "webrick"
