import { readFileSync } from "node:fs";

import { pythonJson } from "./json.ts";

/**
 * `milano schema`: the official document schema specialized to one
 * vocabulary, a port of the specs repository's
 * `tools/generate_document_schema.py` producing the same bytes.
 *
 * Component types become an enum, each component's properties get typed
 * value schemas (literal or `$expr` wrapper), event names constrain `on`,
 * and childless components reject `children`. Producers commit the output
 * next to their documents; every JSON-Schema-aware editor and CI validator
 * then flags mistakes at authoring time, before the gate ever runs. The
 * gate remains the source of truth; this schema is the authoring-time
 * approximation of it (expression result types, action capability, and
 * cross-checks stay gate-only).
 */

export type JsonObject = Record<string, unknown>;

/**
 * The official document schema, `schemas/document.schema.json` in the
 * specs repository, shipped with this package. The SDK's consistency check
 * keeps the copy byte-equal to the specs.
 */
export function documentSchema(): JsonObject {
  return JSON.parse(readFileSync(new URL("../schemas/document.schema.json", import.meta.url), "utf8")) as JsonObject;
}

function isObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function literalSchema(descriptor: unknown): unknown {
  if (typeof descriptor === "string") {
    const optional = descriptor.endsWith("?");
    const kind = descriptor.replace(/\?+$/, "");
    const base: JsonObject =
      { bool: { type: "boolean" }, int: { type: "integer" }, double: { type: "number" } }[kind] ?? { type: "string" };
    return optional ? { anyOf: [base, { type: "null" }] } : base;
  }
  if (isObject(descriptor) && "enum" in descriptor) {
    const base = { enum: [...(descriptor["enum"] as string[])].sort() };
    if (descriptor["optional"] === true) return { anyOf: [base, { type: "null" }] };
    return base;
  }
  if (isObject(descriptor) && "array" in descriptor) {
    return { type: "array", items: literalSchema(descriptor["array"]) };
  }
  return { type: "object" };
}

function valueSchema(descriptor: unknown): unknown {
  return {
    anyOf: [
      literalSchema(descriptor),
      {
        type: "object",
        required: ["$expr"],
        properties: { $expr: { type: "string", minLength: 1 } },
        additionalProperties: false,
      },
    ],
  };
}

/** The official schema specialized to `vocabulary`; the input is left untouched. */
export function specialize(schema: JsonObject, vocabulary: JsonObject): JsonObject {
  const derived = JSON.parse(JSON.stringify(schema)) as JsonObject;
  delete derived["$id"];
  derived["title"] = `Milano documents for vocabulary ${String(vocabulary["name"])}@${String(vocabulary["version"])}`;
  derived["description"] =
    "Generated by generate_document_schema.py; authoring-time validation " +
    "specialized to one vocabulary. The gate remains the source of truth.";

  const components = (vocabulary["components"] ?? {}) as Record<string, JsonObject>;
  const names = Object.keys(components).sort();
  if (names.length === 0) return derived;

  const perComponent: JsonObject[] = [];
  for (const name of names) {
    const component = components[name] as JsonObject;
    const declared = (component["properties"] ?? {}) as Record<string, unknown>;
    const events = Object.keys((component["events"] ?? {}) as JsonObject).sort();
    const properties: JsonObject = {};
    for (const property of Object.keys(declared).sort()) properties[property] = valueSchema(declared[property]);
    const constraints: JsonObject = {
      properties: {
        type: "object",
        propertyNames: { enum: Object.keys(declared).sort() },
        properties,
      },
      on: {
        type: "object",
        propertyNames: { enum: events },
      },
    };
    if (component["children"] !== true) constraints["children"] = { type: "array", maxItems: 0 };
    perComponent.push({
      if: { properties: { type: { const: name } } },
      then: { properties: constraints },
    });
  }

  // The $repeat construct (contract 2.0) belongs to every vocabulary: its
  // own keys are required, a component's keys are not its to carry.
  perComponent.push({
    if: { properties: { type: { const: "$repeat" } } },
    then: {
      required: ["items", "as", "children"],
      properties: {
        properties: { type: "object", maxProperties: 0 },
        on: { type: "object", maxProperties: 0 },
      },
    },
  });

  // The $if construct (contract 2.1), the same way: its own keys are
  // required, and it carries none of a component's.
  perComponent.push({
    if: { properties: { type: { const: "$if" } } },
    then: {
      required: ["condition", "then"],
      properties: {
        properties: { type: "object", maxProperties: 0 },
        on: { type: "object", maxProperties: 0 },
      },
    },
  });

  // The $switch construct (contract 2.1), the same way.
  perComponent.push({
    if: { properties: { type: { const: "$switch" } } },
    then: {
      required: ["subject", "cases"],
      properties: {
        properties: { type: "object", maxProperties: 0 },
        on: { type: "object", maxProperties: 0 },
      },
    },
  });

  const node = (derived["$defs"] as JsonObject)["node"] as JsonObject;
  (node["properties"] as JsonObject)["type"] = {
    enum: [...names, "$if", "$repeat", "$switch"],
  };
  node["allOf"] = perComponent;
  return derived;
}

/** The schema file's text: what `--out` writes, byte for byte the specs tool's. */
export function renderSchema(vocabulary: JsonObject): string {
  return `${pythonJson(specialize(documentSchema(), vocabulary), { indent: 2 })}\n`;
}
